# Generated by Django 6.0.5 on 2026-05-07 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_type', models.CharField(choices=[('Donor', 'Donor'), ('Advisor', 'Advisor'), ('Company', 'Company'), ('Internal', 'Internal')], max_length=20)),
                ('category', models.CharField(choices=[('Grant Help', 'Grant Help'), ('Fund Question', 'Fund Question'), ('Giving Portal Issue', 'Giving Portal Issue'), ('Advisor Request', 'Advisor Request'), ('Scholarship', 'Scholarship'), ('Corporate Giving', 'Corporate Giving'), ('Unique Asset', 'Unique Asset')], max_length=30)),
                ('fund_name', models.CharField(max_length=255)),
                ('grant_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nonprofit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('missing_information', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Review', 'In Review'), ('Waiting on Donor', 'Waiting on Donor'), ('Completed', 'Completed')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('note_type', models.CharField(choices=[('note', 'Note'), ('system', 'System'), ('status_change', 'Status Change')], default='note', max_length=20)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='requests_app.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='AIDraftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_by', models.CharField(max_length=255)),
                ('draft_text', models.TextField()),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_draft_logs', to='requests_app.servicerequest')),
            ],
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='requests_app.staffuser'),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('New', 'New'), ('In Review', 'In Review'), ('Waiting on Donor', 'Waiting on Donor'), ('Completed', 'Completed')], max_length=20)),
                ('new_status', models.CharField(choices=[('New', 'New'), ('In Review', 'In Review'), ('Waiting on Donor', 'Waiting on Donor'), ('Completed', 'Completed')], max_length=20)),
                ('changed_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests_app.servicerequest')),
            ],
        ),
    ]
